### ISSUE TITLE
bump pandas version to 1.5.1 ?

### ISSUE THREAD

**Issue by mapo9** [conda-forge/pretty_html_table-feedstock#11]
### Comment:

Hi @Maarten-vd-Sande ,

we are currently developing a tool that makes heavy use of `pretty-html-table`. 
While trying to add the tool to bioconda, we found out that `pretty-html-table` requires pandas version <=1.25.5.
Unfortunately, we require the version 1.5.1. ...
We had no problems with the pypi version of `pretty-html-table` during development with the higher pandas version. So, `pretty-html-table` works with the pandas version we require. 
Would it be possible to bump the pandas version of the conda-forge version to `<=1.5.1`? It would help us a lot! 

(Our failed biocondas [PR](https://github.com/bioconda/bioconda-recipes/pull/40808))

Best, 
Mark

**Comment by Maarten-vd-Sande** [comment]
Hi Mark,

Can't say I remember why I pinned it. I'll try to update it these days. Sorry to keep your bioconda update hanging 😬

**Comment by Maarten-vd-Sande** [comment]
btw for future reference I think you can open your own PR for these types of changes
https://github.com/conda-forge/pretty_html_table-feedstock/pull/13

**Comment by mapo9** [comment]
Hi,
great thanks!
